format = """
$username \
$directory \
$kubernetes \
$git_branch \
$git_status \
$container \
$fill \
$azure \
\n [ 󱞪 ](fg:iris)
"""
palette = "rose-pine"

[palettes.rose-pine]
overlay = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[directory]
format = "[](fg:overlay)[ $path ]($style)[](fg:overlay)"
style = "bg:overlay fg:pine"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[](fg:overlay)[ $symbol $branch ]($style)[](fg:overlay)"
style = "bg:overlay fg:foam"
symbol = ""

[git_status]
style = "bg:overlay fg:love"
format = '[](fg:overlay)[$all_status$ahead_behind]($style)[](fg:overlay)'
disabled = false
up_to_date = "✓"

[username]
disabled = false
format = "[](fg:overlay)[ 󰧱 $user ]($style)[](fg:overlay)"
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:iris"

[kubernetes]
symbol = '☸ '
format = '[](fg:overlay)[$symbol$context( \($namespace\))]($style)[](fg:overlay)'
disabled = false
style = "bg:overlay fg:foam"

[container]
disabled = false
style = 'bg:overlay fg:iris'
format = '[](fg:overlay)[$symbol ($name)]($style)[](fg:overlay) '

[azure]
disabled = false
format = '[](fg:overlay)[$symbol($subscription)]($style)[](fg:overlay) '
symbol = '󰠅 '
style = 'bg:overlay fg:blue bold'

